version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
    - 3306:3306
