version: '3.7'
services:
  db:
    # image: mysql
    build: ./mysql/
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: empresa
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
    - 3306:3306
